### ISSUE TITLE
Support namespaced operation

### ISSUE THREAD

**Issue by rrati** [blackducksoftware/synopsys-operator#220]
**Is your feature request related to a problem? Please describe.**
Currently the operator works at the cluster level, which means only 1 operator can exist at a time.  This also means cluster level permissions are required to function, which could cause problems for users in more restricted clusters.

If the operator could support running namespaced, and creating namespaced CRDs, then an operator could be isolated to a specific namespace.  This would also allow multiple operators to run in a cluster.

**Comment by dmrit** [comment]
We have a hard time using operators that can't be coerced into a namespace because cluster-admin privileges are restricted in our production K8S cluster.  Registering CRDs isn't an issue for us, but granting create/delete on namespaces, clusterroles, and clusterrolebindings opens up some major concerns.

If this operator could run within a single namespace (or at least with restricted permission to create/delete a fixed set of named namespaces) and not need the ability to create or modify cluster-wide roles and bindings, that'd be helpful for us.
