### ISSUE TITLE
unable to get Custom Resource Definition

### ISSUE THREAD

**Issue by jayunit100** [blackducksoftware/synopsys-operator#820]
```
➜  synopsysctl-stuff ./synopsysctl create blackduck jay --admin-password=jay --postgres-password=jay --user-password=jay
ERRO[0000] synopsyctl failed: unable to get Custom Resource Definition 'blackducks.synopsys.com' in your cluster due to customresourcedefinitions.apiextensions.k8s.io "blackducks.synopsys.com" not found 
```

**Comment by rrati** [comment]
@jayunit100 How did you deploy the operator?  Did you enable blackduck?

**Comment by StevenCane** [comment]
Not sure if this is related to origianl post

**synopsysctl deploy --enable-blackduck --cluster-scoped**
INFO[0000] deploying Synopsys Operator in namespace 'synopsys-operator'... 
INFO[0000] creating CustomResourceDefinition blackducks.synopsys.com 
ERRO[0000] synopsyctl failed: CustomResourceDefinition: Post https://IP_HERE:6443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
/go/src/github.com/blackducksoftware/synopsys-operator/pkg/synopsysctl/cmd_deploy.go:107: unable to deploy custom resource definition

**Comment by yashbhutwala** [comment]
> ERRO[0000] synopsyctl failed: CustomResourceDefinition: Post https://IP_HERE:6443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")

@StevenCane you're facing a different issue, most likely you need to add this flag when running the command `--insecure-skip-tls-verify`.  Seems the certs in your `kubeconfig` are not valid.
